[buildPlans.Zenbones-Mono]
family = "Zenbones Mono"
spacing = "term"
serifs = "sans"
exportGlyphNames = true
buildTextureFeature = true

  [buildPlans.Zenbones-Mono.widths.Normal]
  shape = 548
  menu = 5
  css = "normal"

  [buildPlans.Zenbones-Mono.weights.Thin]
  shape = 125
  menu = 100
  css = 100

  [buildPlans.Zenbones-Mono.weights.ExtraLight]
  shape = 225
  menu = 200
  css = 200

  [buildPlans.Zenbones-Mono.weights.Light]
  shape = 325
  menu = 300
  css = 300

  [buildPlans.Zenbones-Mono.weights.Regular]
  shape = 425
  menu = 400
  css = 400

  [buildPlans.Zenbones-Mono.weights.Medium]
  shape = 500
  menu = 500
  css = 500

  [buildPlans.Zenbones-Mono.weights.SemiBold]
  shape = 600
  menu = 600
  css = 600

  [buildPlans.Zenbones-Mono.weights.Bold]
  shape = 700
  menu = 700
  css = 700

  [buildPlans.Zenbones-Mono.weights.ExtraBold]
  shape = 800
  menu = 800
  css = 800

  [buildPlans.Zenbones-Mono.weights.Heavy]
  shape = 900
  menu = 900
  css = 900

  [buildPlans.Zenbones-Mono.metricOverride]
  xHeight = 550

  [buildPlans.Zenbones-Mono.ligations]
  inherits = "default-calt"
  disables = [
    "lteq",
    "eqlt",
    "gteq",
    "exeq",
    "minus-minus",
    "minus-minus-minus",
    "underscore-underscore",
    "underscore-underscore-underscore"
  ]
  enables = [
    "lteq-separate",
    "eqlt-separate",
    "gteq-separate"
  ]

  [buildPlans.Zenbones-Mono.variants]
  inherits = "ss08"

    [buildPlans.Zenbones-Mono.variants.design]
    two = "straight-neck-serifless"
    three = "flat-top-serifless"
    four = "semi-open-serifless"
    five = "oblique-flat-serifless"
    six = "straight-bar"
    nine = "straight-bar"
    zero = "dotted"
    capital-d = "standard-serifless"
    capital-q = "crossing"
    g = "single-storey-serifless"
    j = "flat-hook-serifed"
    l = "serifed-semi-tailed"
    t = "flat-hook-short-neck"
    tittle = "square"
    diacritic-dot = "square"
    punctuation-dot = "square"
    caret = "low"
    paren = "normal"
    brace = "curly-flat-boundary"
    dollar = "through"
    percent = "rings-continuous-slash"
    cent = "through"
    question = "corner-flat-hooked"

    [buildPlans.Zenbones-Mono.variants.italic]
    a = "single-storey-tailed"
    e = "rounded"
    i = "serifed-flat-tailed"
    f = "tailed"
    y = "cursive-serifless"

[buildPlans.Zenbones-Slab]
family = "Zenbones Slab"
spacing = "term"
serifs = "slab"
exportGlyphNames = true
buildTextureFeature = true

widths.inherits = "buildPlans.Zenbones-Mono"
weights.inherits = "buildPlans.Zenbones-Mono"
ligations.inherits = "buildPlans.Zenbones-Mono"

  [buildPlans.Zenbones-Slab.metricOverride]
  xHeight = 550

  [buildPlans.Zenbones-Slab.variants]
  inherits = "buildPlans.Zenbones-Mono"

  [buildPlans.Zenbones-Slab.variants.design]
    two = "straight-neck-serifed"
    three = "flat-top-serifed"
    four = "semi-open-serifed"
    five = "oblique-flat-serifed"
    capital-d = "standard-bilateral-serifed"
    g = "single-storey-serifed"

    [buildPlans.Zenbones-Slab.variants.italic]
    a = "single-storey-tailed"
    d = "toothed-top-serifed"
    p = "eared-motion-serifed"
    q = "straight-serifless"
    s = "unilateral-serifed"
    y = "cursive-motion-serifed"
    z = "curly-top-serifed"

[buildPlans.Zenbones-Brainy]
family = "Zenbones Brainy"
spacing = "term"
serifs = "sans"
exportGlyphNames = true
buildTextureFeature = true

widths.inherits = "buildPlans.Zenbones-Mono"
weights.inherits = "buildPlans.Zenbones-Mono"
ligations.inherits = "buildPlans.Zenbones-Mono"

  [buildPlans.Zenbones-Brainy.metricOverride]
  xHeight = 550

  [buildPlans.Zenbones-Brainy.variants]
  inherits = "buildPlans.Zenbones-Mono"
  
    [buildPlans.Zenbones-Brainy.variants.design]
    seven = "straight-serifless"
    capital-a = "straight-serifless"
    capital-i = "serifed"
    capital-k = "symmetric-connected-serifless"
    capital-n = "standard-serifless"
    capital-r = "straight-serifless"
    capital-v = "straight-serifless"
    capital-w = "straight-serifless"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    f = "flat-hook-serifless"
    g = "single-storey-flat-hook-serifless"
    k = "symmetric-connected-serifless"
    r = "hookless-serifless"
    v = "straight-serifless"
    w = "straight-serifless"
    x = "straight-serifless"
    y = "straight-serifless"
    z = "straight-serifless"

    [buildPlans.Zenbones-Brainy.variants.italic]
    i = "serifed"
    f = "flat-hook-tailed"
    y = "cursive-flat-hook-serifless"

[buildPlans.Zenbones-Proto]
family = "Zenbones Proto"
spacing = "term"
serifs = "sans"
exportGlyphNames = true
buildTextureFeature = true

widths.inherits = "buildPlans.Zenbones-Mono"
weights.inherits = "buildPlans.Zenbones-Mono"
ligations.inherits = "buildPlans.Zenbones-Mono"

  [buildPlans.Zenbones-Proto.metricOverride]
  xHeight = 550

  [buildPlans.Zenbones-Proto.weights.Regular]
  shape = 475
  menu = 400
  css = 400

  [buildPlans.Zenbones-Proto.weights.Medium]
  shape = 575
  menu = 500
  css = 500

  [buildPlans.Zenbones-Proto.weights.SemiBold]
  shape = 625
  menu = 600
  css = 600

  [buildPlans.Zenbones-Proto.variants]
  inherits = "buildPlans.Zenbones-Mono"
  
    [buildPlans.Zenbones-Proto.variants.design]
    one = "base"
    three = "two-arcs"
    seven = "curly-serifed"
    capital-i = "serifed"
    capital-j = "flat-hook-serifed"
    capital-n = "standard-serifless"
    a = "double-storey-tailed"
    b = "toothed-motion-serifed"
    d = "tailed-serifless"
    f = "tailed"
    g = "double-storey-open"
    h = "straight-top-left-serifed"
    m = "short-leg-serifless"
    p = "eared-motion-serifed"
    q = "tailed-serifless"
    r = "serifed"
    u = "tailed-serifless"
    y = "curly-turn-motion-serifed"

    [buildPlans.Zenbones-Proto.variants.italic]
    a = "single-storey-earless-corner-tailed"
    g = "single-storey-serifless"
    h = "straight-motion-serifed"
    m = "short-leg-tailed-serifless"
    n = "tailed-serifless"
    x = "semi-chancery-straight-serifless"
    y = "cursive-motion-serifed"

[buildPlans.Zenbones-Prose]
family = "Zenbones Prose"
spacing = "quasi-proportional"
serifs = "sans"
noLigation = true

widths.inherits = "buildPlans.Zenbones-Mono"
weights.inherits = "buildPlans.Zenbones-Mono"

  [buildPlans.Zenbones-Prose.metricOverride]
  xHeight = 550

  [buildPlans.Zenbones-Prose.variants]
  inherits = "buildPlans.Zenbones-Mono"

    [buildPlans.Zenbones-Prose.variants.design]
    seven = "straight-serifless"
    capital-a = "straight-serifless"
    capital-k = "straight-serifless"
    capital-n = "standard-serifless"
    capital-r = "straight-serifless"
    capital-v = "straight-serifless"
    capital-w = "straight-flat-top-serifless"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    f = "flat-hook-serifless"
    i = "flat-tailed"
    j = "flat-hook-serifless"
    k = "straight-serifless"
    l = "flat-tailed"
    v = "straight-serifless"
    w = "straight-flat-top-serifless"
    x = "straight-serifless"
    y = "straight-serifless"
    z = "straight-serifless"
    tittle = "round"
    diacritic-dot = "round"
    punctuation-dot = "round"

    [buildPlans.Zenbones-Prose.variants.italic]
    f = "flat-hook-tailed"
    y = "cursive-serifless"
