[buildPlans.ZenbonesMono]
family = "Zenbones Mono"
spacing = "term"
serifs = "sans"
exportGlyphNames = true
buildTextureFeature = true

  [buildPlans.ZenbonesMono.widths.Normal]
  shape = 548
  menu = 5
  css = "normal"

  [buildPlans.ZenbonesMono.weights.regular]
  shape = 425
  menu = 400
  css = 400

  [buildPlans.ZenbonesMono.weights.semibold]
  shape = 600
  menu = 600
  css = 600

  [buildPlans.ZenbonesMono.weights.bold]
  shape = 700
  menu = 700
  css = 700

  [buildPlans.ZenbonesMono.metricOverride]
  xHeight = 550

  [buildPlans.ZenbonesMono.ligations]
  inherits = "default-calt"
  disables = [
    "lteq",
    "eqlt",
    "gteq",
    "exeq"
  ]
  enables = [
    "lteq-separate",
    "eqlt-separate",
    "gteq-separate"
  ]

  [buildPlans.ZenbonesMono.variants]
  inherits = "ss08"

    [buildPlans.ZenbonesMono.variants.design]
    two = "straight-neck-serifless"
    three = "flat-top-serifless"
    four = "semi-open-serifless"
    five = "oblique-flat-serifless"
    six = "straight-bar"
    nine = "straight-bar"
    zero = "dotted"
    capital-d = "standard-serifless"
    capital-q = "crossing"
    g = "single-storey-serifless"
    l = "serifed-semi-tailed"
    u = "toothless-rounded-serifless"
    tittle = "square"
    diacritic-dot = "square"
    punctuation-dot = "square"
    caret = "low"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    dollar = "through"
    percent = "rings-continuous-slash"
    cent = "through"

    [buildPlans.ZenbonesMono.variants.italic]
    a = "single-storey-tailed"
    e = "rounded"
    i = "tailed-serifed"
    f = "tailed"

[buildPlans.ZenbonesSlab]
family = "Zenbones Slab"
spacing = "term"
serifs = "slab"
exportGlyphNames = true
buildTextureFeature = true

widths.inherits = "buildPlans.ZenbonesMono"
ligations.inherits = "buildPlans.ZenbonesMono"

  [buildPlans.ZenbonesSlab.metricOverride]
  xHeight = 550

  [buildPlans.ZenbonesSlab.weights.regular]
  shape = 400
  menu = 400
  css = 400

  [buildPlans.ZenbonesSlab.weights.semibold]
  shape = 600
  menu = 600
  css = 600

  [buildPlans.ZenbonesSlab.weights.bold]
  shape = 700
  menu = 700
  css = 700

  [buildPlans.ZenbonesSlab.variants]
  inherits = "ss08"

    [buildPlans.ZenbonesSlab.variants.design]
    two = "straight-neck-serifed"
    three = "flat-top-serifed"
    four = "semi-open-serifed"
    five = "oblique-flat-serifed"
    six = "straight-bar"
    nine = "straight-bar"
    zero = "dotted"
    capital-d = "standard-bilateral-serifed"
    capital-q = "crossing"
    g = "single-storey-serifed"
    l = "serifed-semi-tailed"
    u = "toothless-rounded-serifed"
    tittle = "square"
    diacritic-dot = "square"
    punctuation-dot = "square"
    caret = "low"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    dollar = "through"
    percent = "rings-continuous-slash"
    cent = "through"

    [buildPlans.ZenbonesSlab.variants.italic]
    a = "single-storey-tailed"
    e = "rounded"
    i = "tailed-serifed"
    f = "tailed"
    p = "eared-motion-serifed"
    q = "straight-serifless"
    s = "unilateral-serifed"
    u = "toothless-rounded-motion-serifed"
    z = "curly-top-serifed"

[buildPlans.ZenbonesBrainy]
family = "Zenbones Brainy"
spacing = "term"
serifs = "sans"
exportGlyphNames = true
buildTextureFeature = true

widths.inherits = "buildPlans.ZenbonesMono"
weights.inherits = "buildPlans.ZenbonesMono"
ligations.inherits = "buildPlans.ZenbonesMono"

  [buildPlans.ZenbonesBrainy.metricOverride]
  xHeight = 550

  [buildPlans.ZenbonesBrainy.variants]
  inherits = "buildPlans.ZenbonesMono"
  
    [buildPlans.ZenbonesBrainy.variants.design]
    seven = "straight-serifless"
    capital-a = "straight-serifless"
    capital-i = "serifed"
    capital-k = "symmetric-connected-serifless"
    capital-n = "standard-serifless"
    capital-r = "straight-serifless"
    capital-v = "straight-serifless"
    capital-w = "straight-flat-top-serifless"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    f = "flat-hook-serifless-crossbar-at-x-height"
    g = "single-storey-flat-hook-serifless"
    j = "flat-hook-serifed"
    k = "symmetric-connected-serifless"
    r = "hookless-serifless"
    t = "flat-hook"
    v = "straight-serifless"
    w = "straight-flat-top-serifless"
    x = "straight-serifless"
    y = "straight-serifless"
    z = "straight-serifless"

    [buildPlans.ZenbonesBrainy.variants.italic]
    f = "flat-hook-tailed-crossbar-at-x-height"
    i = "serifed-flat-tailed"
    y = "cursive-flat-hook-serifless"

[buildPlans.ZenbonesProto]
family = "Zenbones Proto"
spacing = "term"
serifs = "sans"
exportGlyphNames = true
buildTextureFeature = true

widths.inherits = "buildPlans.ZenbonesMono"
weights.inherits = "buildPlans.ZenbonesMono"
ligations.inherits = "buildPlans.ZenbonesMono"

  [buildPlans.ZenbonesProto.metricOverride]
  xHeight = 550

  [buildPlans.ZenbonesProto.weights.regular]
  shape = 475
  menu = 400
  css = 400

  [buildPlans.ZenbonesProto.weights.semibold]
  shape = 625
  menu = 600
  css = 600

  [buildPlans.ZenbonesProto.variants]
  inherits = "buildPlans.ZenbonesMono"
  
    [buildPlans.ZenbonesProto.variants.design]
    one = "base"
    three = "two-arcs"
    seven = "curly-serifed"
    capital-i = "serifed"
    capital-j = "flat-hook-serifed"
    capital-n = "standard-serifless"
    a = "double-storey-tailed"
    b = "toothed-motion-serifed"
    d = "tailed-serifless"
    f = "tailed"
    g = "double-storey-open"
    h = "straight-top-left-serifed"
    j = "flat-hook-serifed"
    m = "short-leg-serifless"
    p = "eared-motion-serifed"
    q = "tailed-serifless"
    r = "serifed"
    t = "flat-hook-short-neck"
    u = "tailed-serifless"
    y = "cursive-motion-serifed"
    at = "compact"

    [buildPlans.ZenbonesProto.variants.italic]
    a = "single-storey-earless-corner-tailed"
    g = "single-storey-serifless"
    h = "straight-motion-serifed"
    i = "tailed-serifed"
    j = "serifed"
    m = "short-leg-tailed-serifless"
    n = "tailed-serifless"
    x = "semi-chancery-straight-serifless"
