name: Release

on:
  push:
    tags: "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        typeface:
          [
            "Zenbones-Mono",
            "Zenbones-Slab",
            "Zenbones-Brainy",
            "Zenbones-Proto",
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install ttfautohint
        run: |
          sudo apt-get update
          sudo apt-get install ttfautohint

      - name: Clone Iosevka
        run: |
          cd ..
          iosevka_version=$(cat ./zenbones-mono/.iosevka-version)
          git clone --depth 1 https://github.com/be5invis/Iosevka.git
          cd Iosevka
          git fetch --tags --quiet
          git checkout tags/${iosevka_version}

      - name: Build Zenbones Mono
        run: |
          cd ../Iosevka
          cp ../zenbones-mono/private-build-plans.toml ./private-build-plans.toml
          npm install
          npm run build -- contents::${{ matrix.typeface }}

      - name: Zip build files
        run: |
          cd ../Iosevka/dist/${{ matrix.typeface }}
          zip -r ${{ matrix.typeface }}-TTF.zip TTF
          zip -r ${{ matrix.typeface }}-TTF-Unhinted.zip TTF-Unhinted
          zip -r ${{ matrix.typeface }}-WOFF2.zip WOFF2 ${{ matrix.typeface }}.css
          zip -r ${{ matrix.typeface }}-WOFF2-Unhinted.zip WOFF2 ${{ matrix.typeface }}-Unhinted.css

      - name: Upload zip file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.typeface }}
          path: /home/runner/work/zenbones-mono/Iosevka/dist/${{ matrix.typeface }}/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: artifacts/*.zip

  call-create-images-workflow:
    needs: release
    uses: ./.github/workflows/create-images.yml
